services:
  chat-client:
    container_name: chat-client
    build: .
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
      - PORT=3000
      - HOSTNAME=0.0.0.0
    ports:
      - "3000:3000"
    networks:
      - chat-client-network
      - proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # Main application route (naked domain)
      - "traefik.http.routers.chat-client.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.chat-client.entrypoints=websecure"
      - "traefik.http.routers.chat-client.tls.certresolver=manual"
      - "traefik.http.routers.chat-client.middlewares=secure-headers"
      - "traefik.http.services.chat-client.loadbalancer.server.port=3000"
      - "traefik.http.routers.chat-client.priority=1"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  chat-client-network:
    driver: bridge
  proxy:
    external: true