services:
  chat-server:
    container_name: chat-server
    build: .
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://chatuser:chatpass@postgres:5432/chatdb
      - CORS_ORIGIN=https://opensourceteacher.ca
      - PORT=3001
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - chat-network
      - proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      
      # API routes (/api/*) - WITH path stripping
      - "traefik.http.routers.chat-server-api.rule=Host(`opensourceteacher.ca`) && PathPrefix(`/api`)"
      - "traefik.http.routers.chat-server-api.entrypoints=websecure"
      - "traefik.http.routers.chat-server-api.tls.certresolver=manual"
      - "traefik.http.routers.chat-server-api.middlewares=api-stripprefix,secure-headers"
      - "traefik.http.routers.chat-server-api.service=chat-server"
      - "traefik.http.routers.chat-server-api.priority=10"
      
      # Socket.IO routes (/socket.io/*) - WITHOUT path stripping
      - "traefik.http.routers.chat-server-socket.rule=Host(`opensourceteacher.ca`) && PathPrefix(`/socket.io`)"
      - "traefik.http.routers.chat-server-socket.entrypoints=websecure"
      - "traefik.http.routers.chat-server-socket.tls.certresolver=manual"
      - "traefik.http.routers.chat-server-socket.middlewares=secure-headers"
      - "traefik.http.routers.chat-server-socket.service=chat-server"
      - "traefik.http.routers.chat-server-socket.priority=10"
      
      # Service definition
      - "traefik.http.services.chat-server.loadbalancer.server.port=3001"
      
      # Strip /api prefix middleware (only applied to API routes)
      - "traefik.http.middlewares.api-stripprefix.replacepathregex.regex=^/api/(.*)"
      - "traefik.http.middlewares.api-stripprefix.replacepathregex.replacement=/$${1}"

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chat-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatuser -d chatdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  chat-network:
    driver: bridge
  proxy:
    external: true